### ISSUE TITLE
Org special blocks not rendering

### ISSUE THREAD

**Issue by OolonColoophid** [kawabata/ox-pandoc#48]
Hi there

My Org file (snippet):

`
\begin{answer}
This is raw latex, and works
\end{answer}

#+BEGIN_answer
This is an example of an Org special block, which should work... but does not.
#+END_answer
`

The lower BEGIN block is a special block, and should be converted to a Latex environment (answer) when I export to Latex-PDF using Pandoc. I, should, therefore, see the text in two 'answer' environments. I do not, however. Only the first renders.

The intermediate Latex shows this:

`\begin{answer}
This is raw latex, and works
\end{answer}

This is an example of an Org special block, which should work\ldots{}
but does not.`

The second paragraph isn't getting the environment set.

If I use export to Latex outside of Pandoc, the second paragraph *does* get the correct environment. Any idea what I'm doing wrong?

Best wishes

Ian

**Comment by tarleb** [comment]
This is due to pandoc's way of converting: All documents are parsed into a pandoc-internal document representation.  This, of course, results in some loss of information in some cases. While the name of the block is still present in that intermediate representation, pandoc's LaTeX writer doesn't know that it should be used as an environment name. The information is simply discarded.

This could probably be solved by shipping a small lua filter with ox-pandoc, which would ensure that the necessary information is added back in. @kawabata, is this feasible?

**Comment by OolonColoophid** [comment]
Hi tarleb

Thanks for looking at this - I appreciate it.

This works swimmingly.

If anyone else is reading this, I had to update Pandoc from 2.0.3 to 2.1.1 to get this to work.

Cheers

Ian
